# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a433c69b4c188aab93ebeca67dcbaca2860af841e13f90ecf814893e66245b90bc03031da036413b8e692f6c1805a718606886ef28341d2f9821655c3d72541

test:
  secret_key_base: 351ef3bb038351f7776033f67748f7ae146fc1270ee0a0117097a8e8b69274a9aa032d5781f525f2cc0d9def491a529d7196babc7e1b357c1f5976021189770c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
